/* Generated by tools/make_crab_lottie.py - do not edit. */
#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Ordered worst-to-best mood is NOT meaningful here; the firmware
// picks by name via crab_mood_asset().
typedef enum {
    CRAB_HAPPY,
    CRAB_FOCUSED,
    CRAB_CHILL,
    CRAB_SLEEPY,
    CRAB_ASLEEP,
    CRAB_ROCKING,
    CRAB_MOOD_COUNT,
} CrabMood;

typedef struct {
    const uint8_t *data;
    size_t size;
} CrabAsset;

// Indexed by CrabMood.
extern const CrabAsset crab_mood_assets[CRAB_MOOD_COUNT];

#ifdef __cplusplus
}
#endif
