#!/usr/bin/env python3
"""Convert a Lottie JSON file into the C byte array the firmware embeds.

    python tools/lottie_to_c.py crab.json src/lottie_asset.c

The array is emitted as raw bytes, so what lands in flash is the JSON's own
size (the .c source file is ~6x larger, but that's just hex text the compiler
throws away).

Render cost, not size, is the real constraint: ThorVG rasterises in software
and pegs the ESP32 near 90% CPU while animating. Flash has roughly 4.8MB free.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

SYMBOL = "lottie_mascot_asset"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__)
        return 2

    src = Path(argv[1])
    dst = Path(argv[2])

    data = src.read_bytes()

    # Fail early on malformed JSON rather than shipping something ThorVG will
    # choke on at runtime, where the only symptom is a blank canvas.
    try:
        json.loads(data)
    except json.JSONDecodeError as e:
        print(f"error: {src} is not valid JSON: {e}", file=sys.stderr)
        return 1

    lines = [
        f"/* {SYMBOL} - generated by tools/lottie_to_c.py from {src.name}\n",
        " * Do not edit by hand; regenerate instead.\n",
        " */\n\n",
        "#include <stddef.h>\n#include <stdint.h>\n\n",
        f"const uint8_t {SYMBOL}[] = {{\n",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    lines.append("};\n\n")
    lines.append(f"const size_t {SYMBOL}_size = sizeof({SYMBOL});\n")

    dst.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {dst} ({len(data):,} bytes of JSON -> {dst.stat().st_size:,} bytes of C)")
    if len(data) > 50 * 1024:
        print(f"note: {len(data)/1024:.0f}KB is on the large side; complex animations "
              f"cost more CPU to rasterise, and this board is already ~90% busy while animating.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
